CREATE DATABASE IF NOT EXISTS nexa_growth
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE nexa_growth;

CREATE TABLE IF NOT EXISTS contatos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  mensagem TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
